version: "3.8"

services:
  belajar-untuk-kerja/aplikasi-bank/bank-be/bank-backend-app:
    image: haris2/bank-be:belajar-untuk-kerja/aplikasi-bank/bank-be/bank-backend-latest
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - bank-kafka
      - bank-db

  bank-worker-app:
    image: haris2/bank-be:bank-worker-latest
    restart: on-failure
    depends_on:
      - bank-kafka
      - bank-db

  bank-db:
    image: postgres:16.4-alpine3.20
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: haris123
      POSTGRES_DB: bank_db
    volumes:
      - bank_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bank-zk:
    image: confluentinc/cp-zookeeper:7.5.1
    hostname: bank-zk
    restart: on-failure
    container_name: bank-zk
    platform: linux/amd64
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: bank-zk:2888:3888
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      TZ: "Asia/Jakarta"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "1G"
        reservations:
          cpus: "0.15"
          memory: "256M"

  bank-kafka:
    image: confluentinc/cp-kafka:7.5.1
    hostname: bank-kafka
    restart: on-failure
    container_name: bank-kafka
    depends_on:
      - bank-zk
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "172.17.0.1:2181"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.17.0.1:9092,PLAINTEXT_HOST://172.17.0.1:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      TZ: "Asia/Jakarta"

volumes:
  bank_data:
