server:
  port: 8080
  read_timeout: 1
  write_timeout: 1

db:
  host: localhost
  port: 5433
  user: postgres
  password: yoontae93
  db_name: bank_db
  ssl_mode: disable
  min_conn: 5
  max_conn: 1000

kafka:
  broker: localhost:9092

process_transfer_topic: bank.transfer_created
